context:
  version: "0.6.1"

package:
  name: gh-enhance
  version: ${{ version }}

source:
  url: https://github.com/dlvhdr/gh-enhance/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 202096e1a2ca97bbce3358aef41b75c8086edb8e7456b5a2feffba613ad99ae7
  target_directory: src

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - if: unix
      then: go build -v -tags=nodbus -o $PREFIX/bin/gh-enhance -ldflags="-s -w"
      else: go build -v -tags=nodbus -o %LIBRARY_BIN%\gh-enhance.exe -ldflags="-s"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script: gh-enhance --help
  - package_contents:
      bin:
        - gh-enhance
      strict: true

about:
  homepage: https://github.com/dlvhdr/gh-enhance
  summary: A blazingly fast terminal UI for GitHub Actions
  description: |
    gh-enhance is a terminal user interface for GitHub Actions that provides
    fast, interactive access to view and manage GitHub Actions workflows
    directly from your terminal.
  license: MIT
  license_file:
    - src/LICENSE
    - library_licenses/
  repository: https://github.com/dlvhdr/gh-enhance

extra:
  recipe-maintainers:
    - pavelzw
